server:
  port: 8088

spring:
  application:
    name: cms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

feign:
  okhttp:
    enabled: true
  autoconfiguration:
    jackson:
      enabled: true
